name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x] # Use the appropriate Node.js version

    env:
      SERVER_DIR: 'http://43.204.231.175/3000/' # Set the server directory

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Server
        run: |
          # Use SCP to upload build files to the server
          scp -r build/* your-username@43.204.231.175:/path/to/remote/directory
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        shell: bash
